[package]
name = "bevy_mod_bbcode"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"

[dependencies.bevy]
version = "0.14"
default-features = false
features = ["bevy_text", "bevy_ui"]

[dev-dependencies.bevy]
version = "0.14"
